In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, confusion_matrix, classification_report
)
import joblib

# Verify Versions
print(f"✅ Pandas: {pd.__version__}")
print(f"✅ NumPy: {np.__version__}")
print(f"✅ Scikit-learn: {__import__('sklearn').__version__}")
print("✅ All libraries loaded successfully — NO ERRORS")

✅ Pandas: 2.2.2
✅ NumPy: 1.26.4
✅ Scikit-learn: 1.5.2
✅ All libraries loaded successfully — NO ERRORS

In [4]:
# Load CSV File
df = pd.read_csv("StudentFiles.csv")
print(f"✅ Dataset Loaded | Rows: {df.shape[0]}, Columns: {df.shape[1]}")
df.head()

✅ Dataset Loaded | Rows: 10, Columns: 14

,Student_ID,Course,Year_Level,Semester,No. Departments,Schedule,Payment_Status,Payment_Minutes_Verify_Time,Department_Count,Request_Date,Report_Mat,Submitted_Date,Prev.Avg_Approval,Total_Days
0,BSIT001,BSIT,3rd,2nd,5,"2025-04-13, 2026-04-14",1,5,3,4/12/2025,3,4/13/2025,30,2
1,BSIT002,BSIT,2nd,2nd,5,"2025-04-10, 2026-04-11",1,10,2,4/9/2025,2,4/10/2025,120,2
2,BSIT003,BSIT,2nd,2nd,5,"2025-04-10, 2026-04-11",1,30,1,4/9/2025,1,4/11/2025,15,2
3,BSIT004,BSIT,4th,2nd,5,"2025-04-16, 2025-04-17",0,15,2,4/15/2025,2,4/16/2025,15,2
4,BSIT005,BSIT,3rd,2nd,5,"2025-04-13, 2026-04-14",0,5,3,4/12/2025,2,4/14/2025,2880,3

In [5]:
# Encode Text → Numbers
course_map = {'BSIT': 1, 'BSit': 1}
year_map = {'1st':1, '2nd':2, '3rd':3, '4th':4}
sem_map = {'1st':1, '2nd':2}

df['Course'] = df['Course'].map(course_map)
df['Year_Level'] = df['Year_Level'].map(year_map)
df['Semester'] = df['Semester'].map(sem_map)

# Fill missing values
df = df.fillna(df.mean(numeric_only=True))
print("✅ Data preprocessing complete")
df.head()

✅ Data preprocessing complete

,Student_ID,Course,Year_Level,Semester,No. Departments,Schedule,Payment_Status,Payment_Minutes_Verify_Time,Department_Count,Request_Date,Report_Mat,Submitted_Date,Prev.Avg_Approval,Total_Days
0,BSIT001,1,3,2,5,"2025-04-13, 2026-04-14",1,5,3,4/12/2025,3,4/13/2025,30,2
1,BSIT002,1,2,2,5,"2025-04-10, 2026-04-11",1,10,2,4/9/2025,2,4/10/2025,120,2
2,BSIT003,1,2,2,5,"2025-04-10, 2026-04-11",1,30,1,4/9/2025,1,4/11/2025,15,2
3,BSIT004,1,4,2,5,"2025-04-16, 2025-04-17",0,15,2,4/15/2025,2,4/16/2025,15,2
4,BSIT005,1,3,2,5,"2025-04-13, 2026-04-14",0,5,3,4/12/2025,2,4/14/2025,2880,3

In [6]:
# --------------------------
# CLASSIFICATION PROBLEM
# Predict Payment Status: 0 = Not Paid, 1 = Paid
# --------------------------

# Features & Target
X_class = df[['Course', 'Year_Level', 'Semester', 'Department_Count', 'Report_Mat', 'Prev.Avg_Approval']]
y_class = df['Payment_Status']

# Split Data: 80% Train, 20% Test
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_class, y_class, test_size=0.2, random_state=42)

# Train Model
class_model = LogisticRegression(max_iter=1000)
class_model.fit(X_train_c, y_train_c)

# Predict
y_pred_c = class_model.predict(X_test_c)

# Evaluation Metrics
print(f"✅ Classification Accuracy: {accuracy_score(y_test_c, y_pred_c):.4f}")
print("\n📊 Confusion Matrix:")
print(confusion_matrix(y_test_c, y_pred_c))
print("\n📋 Classification Report:")
print(classification_report(y_test_c, y_pred_c))

# Save Model
joblib.dump(class_model, "classification_model.pkl")
print("✅ Classification Model Saved")

✅ Classification Accuracy: 0.5000

📊 Confusion Matrix:
[[0 1]
 [0 1]]

📋 Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      1.00      0.67         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

✅ Classification Model Saved

c:\Users\user\Desktop\Jupyter-SAIS\Time_Predictor\C_Model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\user\Desktop\Jupyter-SAIS\Time_Predictor\C_Model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\user\Desktop\Jupyter-SAIS\Time_Predictor\C_Model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [7]:
# --------------------------
# REGRESSION PROBLEM
# Predict Total Processing Days (Continuous Value)
# --------------------------

# Features & Target
X_reg = df[['Course', 'Year_Level', 'Semester', 'Payment_Status', 'Department_Count', 'Report_Mat', 'Prev.Avg_Approval']]
y_reg = df['Total_Days']

# Split Data
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

# Train Model
reg_model = LinearRegression()
reg_model.fit(X_train_r, y_train_r)

# Predict
y_pred_r = reg_model.predict(X_test_r)

# Evaluation Metrics
print(f"✅ MAE: {mean_absolute_error(y_test_r, y_pred_r):.4f}")
print(f"✅ MSE: {mean_squared_error(y_test_r, y_pred_r):.4f}")
print(f"✅ RMSE: {np.sqrt(mean_squared_error(y_test_r, y_pred_r)):.4f}")
print(f"✅ R² Score: {r2_score(y_test_r, y_pred_r):.4f}")

# Save Model
joblib.dump(reg_model, "regression_model.pkl")
print("✅ Regression Model Saved")

✅ MAE: 0.0362
✅ MSE: 0.0013
✅ RMSE: 0.0362
✅ R² Score: 0.0000
✅ Regression Model Saved

In [8]:
print("""
✅ Successfully built Classification Model
✅ Successfully built Regression Model
✅ Evaluation metrics computed
✅ Models saved successfully
✅ Ready for Streamlit deployment
""")

✅ Successfully built Classification Model
✅ Successfully built Regression Model
✅ Evaluation metrics computed
✅ Models saved successfully
✅ Ready for Streamlit deployment